services:
  - type: web
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon
    autoDeploy: true

    healthCheckPath: /healthz
    initialDelaySeconds: 30
    rootDirectory: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT ml_pipeline:app
