# render.yaml
services:
  - type: web_service
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon

    # point Render at the folder where your Flask app lives:
    rootDirectory: .

    # install your Python deps:
    buildCommand: pip install -r requirements.txt

    # launch your Flask app (app = Flask(__name__)):
    startCommand: gunicorn ml_pipeline:app
