# render.yaml
services:
  - type: web_service
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon

    # ← Pin to a version that has binary wheels for pandas, numpy, scikit-learn, etc.
    pythonVersion: 3.11.10

    # ← point at your Flask app & requirements
    rootDirectory: .

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_pipeline:app
