# render.yaml
services:
  - type: web
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon

    # install your deps
    buildCommand: pip install -r requirements.txt

    # launch your Flask app
    startCommand: gunicorn ml_pipeline:app
