services:
  - type: web
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"

    rootDirectory: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_pipeline:app
