# render.yaml
services:
  - type: web
    name: fx-ai-pipeline
    env: python
    plan: free
    region: oregon
    autoDeploy: true

    envVars:
      - key: OPENAI_API_KEY
        fromSecret: true

    healthCheckPath: /healthz
    rootDirectory: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn --workers 1 --threads 4 --bind 0.0.0.0:$PORT ml_pipeline:app
